### PR TITLE
bug: handles null pointer exception in youtububeorinstagram method in…

### LINKED ISSUE #959: [BUG] NULL POINTER EXCEPTION IN FILEDOWNLOADER
### Describe the bug

NullPointerException risk in downloadYoutubeOrInstagram:
You do Objects.requireNonNull(process).getInputStream(). If process is null because processBuilder.start() failed, it will throw NPE. Better to check if process != null before reading its streams.

### Steps To Reproduce

Configure the program to use an invalid or missing path for the yt-dlp executable (Program.YT_DLP).

Run the downloader on a valid YouTube or Instagram link.

The process fails to start (processBuilder.start() throws IOException or returns null).

The method attempts to read from process.getInputStream() without checking for null.

A NullPointerException is thrown at this line:

java
Copy
Edit
try (BufferedReader reader = new BufferedReader(new InputStreamReader(Objects.requireNonNull(process).getInputStream()))) {

### Expected Behavior

_No response_

### Operating System / Environment

Windows 🪟

### Screenshots

_No response_

### Additional information

_No response_

### Do you want to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by siddu017**
This PR fixes a NullPointerException that could occur if the download process failed to start. 
The method now safely checks if the process was successfully created before attempting to read its output or wait for completion.

Fixes #959

### CODE REVIEW

**Comment by siddu017** [comment]
@SaptarshiSarkar12 The PR is ready. Vercel deployment is pending authorization. Please review and approve when you get a chance. Thanks!

**Comment by SaptarshiSarkar12** [comment]
@siddu017 Thank you for the quick fix 😁.
I have approved the Vercel deployment and I'll review it soon.

File: GUI/src/main/java/backend/FileDownloader.java [hunk 1]
```diff
@@ -113,19 +113,22 @@ protected Integer call() {
         updateProgress(0.0, 1.0);
         done = true;
         return exitCode;
+        //no extra space
```
Comment (SaptarshiSarkar12) [inline GUI/src/main/java/backend/FileDownloader.java:116]: Please remove this line.

```suggestion
```

File: desktop.ini
Comment (SaptarshiSarkar12) [inline desktop.ini:1]: This file doesn't appear to be necessary for the project. Could you please remove it?

File: GUI/src/main/java/backend/FileDownloader.java [hunk 2]
```diff
@@ -113,19 +113,22 @@ protected Integer call() {
...
     }
 
     private void downloadYoutubeOrInstagram(boolean isSpotifySong) {
         String[] fullCommand = new String[]{YT_DLP, "--quiet", "--progress", "-P", dir, downloadLink, "-o", filename, "-f", (isSpotifySong ? "bestaudio" : "mp4")};
         ProcessBuilder processBuilder = new ProcessBuilder(fullCommand);
         sendInfoMessage(String.format(DOWNLOADING_F, filename));
         Process process = null;
+        int exitCode = -1;
```
Comment (SaptarshiSarkar12) [inline GUI/src/main/java/backend/FileDownloader.java:124]: I don't think this initialisation of the local `exitCode` variable is required. An `exitCode` object variable is already declared at [line 50](https://github.com/SaptarshiSarkar12/Drifty/blob/725113cab301a48f970817bb02ea6e6e21150af7/GUI/src/main/java/backend/FileDownloader.java#L50) and initialised to **1** by default (a standard generic error code).
Could you please remove this line?

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
@siddu017 Thank you for the great work! 👏
I’ve reviewed your PR. Could you please address the requested changes?

**Comment by siddu017** [comment]
@SaptarshiSarkar12 addressed and resolved the requested changes

**Review by SaptarshiSarkar12 — APPROVED** [review]
@siddu017 **Looks good to merge 👍.** 
**Thanks for contributing 🚀 🚀.**
You may join our _Discord server_ - **https://discord.gg/DeT4jXPfkG** to get updates about the project.
